name: The Petting Zoo
url: http://pettingzoo.jayperryworks.com
baseurl: 

markdown: redcarpet
pygments: true

exclude: ["README.md", "config.rb", ".sublime-project", ".sublime-workspace", "Guardfile", "Gemfile", "Gemfile.lock", ".sass-cache"]