# jekyll settings
name: The Petting Zoo
tag: "Share & Smile"
# url: http://pettingzoo.jayperryworks.com
baseurl: 

markdown: redcarpet
pygments: true

exclude: ["README.md", "config.rb", ".sublime-project", ".sublime-workspace", "Guardfile", "Gemfile", "Gemfile.lock", ".sass-cache", "assets/media/*"]

# asset paths
assets:
  img: '/assets/images/'
  css: '/assets/css/'
  js: '/assets/js/'
  fonts: '/assets/fonts/'
  s3: 'http://pettingzoo.s3.amazonaws.com'
  carousel: '/banners/carousel/'
  promos: '/banners/promos/'
  catalog: '/catalogs/'
  product: '/products/'
  staff: '/staff/'
  blog: '/blog/'

# prose.io settings
prose:
  rooturl: "_posts"
  media: "uploads"
  ignore:
    - index.md
    - index.html
    - _config.yml
    - /_layouts
    - /_includes

  metadata:
    _posts/about:
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "categories"
        field:
          element: "hidden"
          value: "about"
      - name: "feature"
        field:
          element: "text"
          label: "Feature Image"
          help: "Enter the name of the uploaded feature image (including extension)"
      - name: "feature_caption"
        field:
          element: "text"
          label: "Feature Image Caption"
          help: "Enter a caption (if needed) for the feature image"

    _posts/banners:
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "categories"
        field:
          element: "select"
          options:
            - name: "Carousel"
              value: "carousel"
            - name: "Promos"
              value: "promos"

    _posts/home:
      - name: "layout"
        field:
          element: "hidden"
          value: "default"

    _posts/news:
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "category"
        field:
          element: "hidden"
          value: "blog"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          alterable: "true"
          options:
            - name: "Shows"
              value: "shows"

    _posts/products/catalogs:
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "category"
        field:
          element: "hidden"
          value: "catalog"
      - name: "pdf"
        field:
          element: "text"
          label: "PDF Version"
          help: "Enter the name of the uploaded PDF (including extension)"
      - name: "cover"
        field:
          element: "text"
          label: "Cover Image"
          help: "Enter the name of the uploaded cover image (including extension)"

    _posts/products/custom:
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "category"
        field:
          element: "hidden"
          value: "custom"

    _posts/staff:
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "category"
        field:
          element: "hidden"
          value: "staff"
      - name: "job_title"
        field:
          element: "text"
          label: "Job Title"
      - name: "email"
        field:
          element: "text"
          label: "Email Address"
      - name: "portrait"
        field:
          element: "text"
          label: "Portrait Image"
          help: "Enter the name of the uploaded portrait image (including extension)"

    _posts/testimonials:
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "category"
        field:
          element: "hidden"
          value: "testimonials"
