# jekyll settings
name: The Petting Zoo
tag: "Share & Smile"
#url: 'http://pettingzooplush.com'
baseurl: 
permalink: /:categories/:title/

markdown: redcarpet
pygments: true


exclude: ["README.md", "config.rb", ".sublime-project", ".sublime-workspace", "Guardfile", "Gemfile", "Gemfile.lock", ".sass-cache", "assets/media/*"]

# asset paths
assets:
  img: "/assets/images/"
  css: "/assets/css/"
  js: "/assets/js/"
  fonts: "/assets/fonts/"
  s3: "http://pettingzoo-website.s3.amazonaws.com"
  carousel: "/banners/carousel/"
  promos: "/banners/promos/"
  catalog: "/products/catalogs/"
  custom: "/products/custom/"
  staff: "/staff/"
  blog: "/blog/"

# prose.io settings
prose:
  rooturl: "_posts"
  media: "uploads"
  ignore:
    - index.md
    - index.html
    - _config.yml
    - /_layouts
    - /_includes

  metadata:
    _posts/about:
      - name: "title"
        field:
          element: "text"
          label: "Page Title"
          help: "Enter the title of the about page"
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "categories"
        field:
          element: "hidden"
          value: "about"
      - name: "feature"
        field:
          element: "text"
          label: "Feature Image"
          help: "Enter the name of the uploaded feature image (including extension)"
      - name: "feature_caption"
        field:
          element: "text"
          label: "Feature Image Caption"
          help: "Enter a caption (if needed) for the feature image"

    _posts/banners:
      - name: "title"
        field:
          element: "hidden"
          value: "Promo Banners"
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "categories"
        field:
          element: "select"
          options:
            - name: "Carousel"
              value: "carousel"
            - name: "Promos"
              value: "promos"

    _posts/home:
      - name: "title"
        field:
          element: "hidden"
          value: "Home"
      - name: "layout"
        field:
          element: "hidden"
          value: "default"

    _posts/news:
      - name: "title"
        field:
          element: "text"
          label: "News Title"
          help: "Enter the title of the news post"
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "category"
        field:
          element: "hidden"
          value: "blog"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          alterable: "true"
          options:
            - name: "Shows"
              value: "shows"

    _posts/products/catalogs:
      - name: "title"
        field:
          element: "text"
          label: "Page Title"
          help: "Enter the title of the about page"
      - name: "layout"
        field:
          element: "hidden"
          value: "catalog"
      - name: "category"
        field:
          element: "hidden"
          value: "catalog"
      - name: "pdf"
        field:
          element: "text"
          label: "PDF Version"
          help: "Enter the name of the uploaded PDF (including extension)"
      - name: "cover"
        field:
          element: "text"
          label: "Cover Image"
          help: "Enter the name of the uploaded cover image (including extension)"

    _posts/products/items:
      - name: "title"
        field:
          element: "text"
          label: "Product Name"
          help: "Enter the product name"
      - name: "catalog"
        field:
          element: "text"
          label: "Catalog Name"
          help: "Enter the catalog where this product appears"
      - name: "collection"
        field:
          element: "text"
          label: "Collection Name"
          help: "(Optional) Enter the collection this product is a part of"
      - name: "photos"
        field:
          element: "textarea"
          label: "Product Photos"
          help: "Add URLs for product photos. Put a '-' in front of each."
      - name: "layout"
        field:
          element: "hidden"
          value: "product"
      - name: "category"
        field:
          element: "hidden"
          value: "products"
      - name: "item"
        field:
          element: "text"
          label: "Item Number"
          help: "Enter the item code"
      - name: "size"
        field:
          element: "text"
          label: "Size"
          help: "Enter the product's size"
      - name: "case"
        field:
          element: "text"
          label: "Case PK"
          help: "Enter the case size (per-pack)"
      - name: "master"
        field:
          element: "text"
          label: "Master Case"
          help: "Enter the master case size"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Product Tags"
          placeholder: "Choose Tags"
          alterable: "true"
          options:
            - name: "Large"
              value: "large"

    _posts/products/custom:
      - name: "title"
        field:
          element: "text"
          label: "Product Name"
          help: "Enter the name of the custom product"
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "category"
        field:
          element: "hidden"
          value: "custom"

    _posts/staff:
      - name: "title"
        field:
          element: "text"
          label: "Staff Name"
          help: "Enter the staff member's name"
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "category"
        field:
          element: "hidden"
          value: "staff"
      - name: "job_title"
        field:
          element: "text"
          label: "Job Title or Region"
      - name: "email"
        field:
          element: "text"
          label: "Email Address"
      - name: "portrait"
        field:
          element: "text"
          label: "Portrait Image"
          help: "Enter the name of the uploaded portrait image (including extension)"

    _posts/testimonials:
      - name: 'title'
        field:
          element: 'text'
          label: 'Customer Name'
          help: 'Enter the name of your happy customer'
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "category"
        field:
          element: "hidden"
          value: "testimonials"
