name: The Petting Zoo
url: http://pettingzoo.jayperryworks.com
baseurl: 

markdown: redcarpet
pygments: true

exclude: ["README.md", "config.rb", ".sublime-project", ".sublime-workspace", "Guardfile", "Gemfile", "Gemfile.lock", ".sass-cache"]

prose:
  rooturl: '_posts'
  media: 'uploads'
  ignore:
    - index.md
    - index.html
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts/about:
      - name: 'layout'
        field:
          element: 'hidden'
          value: 'default'
      - name: 'categories'
        field:
          element: 'hidden'
          value:
          - 'about'
          - 'intro'
      - name: 'feature_image'
        field:
          element: 'text'
          label: 'Feature Image Name (including extension)'
          help: 'Enter the name of the uploaded feature image'
      - name: 'feature_caption'
        field:
          element: 'text'
          label: 'Feature Image Caption'
          help: 'Enter a caption (if needed) for the feature image'

    _posts/home:
      - name: 'layout'
        field:
          element: 'hidden'
          value: 'default'
      - name: 'categories'
        field:
          element: 'hidden'
          value: 'home'

    _posts/news:
      - name: 'layout'
        field:
          element: 'hidden'
          value: 'default'
      - name: 'categories'
        field:
          element: 'hidden'
          value: 'news'

    _posts/products/catalogs:
      - name: 'layout'
        field:
          element: 'hidden'
          value: 'default'
      - name: 'categories'
        field:
          element: 'hidden'
          value: 'catalog'

    _posts/products/custom:
      - name: 'layout'
        field:
          element: 'hidden'
          value: 'default'
      - name: 'categories'
        field:
          element: 'hidden'
          value: 'custom'

    _posts/staff:
      - name: 'layout'
        field:
          element: 'hidden'
          value: 'default'
      - name: 'categories'
        field:
          element: 'hidden'
          value: 'staff'

    _posts/testimonials:
      - name: 'layout'
        field:
          element: 'hidden'
          value: 'default'
      - name: 'categories'
        field:
          element: 'hidden'
          value: 'testimonial'
